# -*- coding: utf-8 -*-
"""metaverse_missions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYXrWNhAIKQS0i_6HWiAjGgpqthZ7X7g
"""

import pandas as pd
import numpy as np

# -------------------------
# 1. LOAD THE DATASET
# -------------------------
df = pd.read_csv("mission1_traffic_activity_dataset.csv")

# -------------------------
# 2. FEATURE TRANSFORMATIONS
# -------------------------

df["log_density"] = np.log10(df["vehicle_density (cars/min)"] + 1)
df["log_speed"] = np.log10(df["avg_speed"] + 1)
df["log_public_transport"] = np.log10(df["public-transport-frequency"] + 1)
df["log_trucks"] = np.log10(df["truck_arrival_frequency"] + 1)

# -------------------------
# 3. WEIGHTED SUM (ACOUSTIC MODEL)
# -------------------------

df["base_noise"] = (
    12 * df["log_density"] +
    10 * df["average_honking_probability"] +
    6 * df["log_speed"] +
    8 * df["log_trucks"] +
    4 * df["log_public_transport"]
)

# -------------------------
# 4. EVENT & HUMAN ACTIVITY NOISE
# -------------------------

df["event_noise"] = 5 * (df["special_event_traffic_multiplier"] - 1)
df["gathering_noise"] = 7 * df["public-gathering-indicator"]

# -------------------------
# 5. INDUSTRIAL NOISE MODEL
# -------------------------

def industrial_noise(row):
    if row["factory_id"] == 0:
        return 0
    if row["shift_start_end"] == "Day":
        return 5
    if row["shift_start_end"] == "Night":
        return 8
    if row["shift_start_end"] == "Double":
        return 10
    return 0

df["industrial_noise"] = df.apply(industrial_noise, axis=1)

# -------------------------
# 6. FINAL NOISE LEVEL PREDICTION (dBA)
# -------------------------

df["Predicted_Noise_dBA"] = (
    50 +
    df["base_noise"] +
    df["event_noise"] +
    df["gathering_noise"] +
    df["industrial_noise"]
)

# Clip to realistic limits
df["Predicted_Noise_dBA"] = df["Predicted_Noise_dBA"].clip(40, 110)

# -------------------------
# 7. SHOW OUTPUT IN COLAB
# -------------------------

print("✔ Predicted Noise Levels for 500m City Grid Zones:")
df_output = df[[
    "timestamp",
    "zone_id",
    "vehicle_density (cars/min)",
    "avg_speed",
    "traffic_pattern_type",
    "average_honking_probability",
    "truck_arrival_frequency",
    "public-gathering-indicator",
    "factory_id",
    "shift_start_end",
    "Predicted_Noise_dBA"
]]

df_output.head(20)   # shows first 20 rows

# Display in Colab table
df_output.head(20)

# -------------------------
# 8. SAVE FINAL CSV
# -------------------------

df.to_csv("mission1_noise_predicted_dataset.csv", index=False)

print("\n✔ File generated: mission1_noise_predicted_dataset.csv")

import os
os.listdir("/content")

df_output.tail(10)

import pandas as pd

df = pd.read_csv("/content/mission1_noise_predicted_dataset.csv")
df.head()

df['timestamp'] = pd.to_datetime(df['timestamp'])
df['hour'] = df['timestamp'].dt.hour

def classify_noise(row):
    # noise rules
    limit = 55 if row['hour'] >= 22 or row['hour'] < 6 else 65

    if row['Predicted_Noise_dBA'] > limit:
        return "Red"
    elif row['Predicted_Noise_dBA'] > 0.9 * limit:
        return "Yellow"
    else:
        return "Green"

df['zone_status'] = df.apply(classify_noise, axis=1)
df.head()

df = df.sort_values(['zone_id','timestamp'])

alerts = []

for zone in df['zone_id'].unique():
    zdf = df[df['zone_id'] == zone].copy()
    zdf = zdf.set_index("timestamp").resample("10min").first()
    zdf['is_red'] = zdf['zone_status'] == "Red"

    zdf['persistent'] = zdf['is_red'].rolling(3).sum() == 3

    if zdf['persistent'].any():
        alerts.append(zone)

alerts

!pip install folium branca

import numpy as np

def generate_lat_lon(zone_id, base_lat=12.9716, base_lon=77.5946):
    offset = 0.005   # ~500m
    zone = zone_id - 1
    r = zone // 5    # row
    c = zone % 5     # col
    lat = base_lat + r * offset
    lon = base_lon + c * offset
    return lat, lon

df["lat"], df["lon"] = zip(*df["zone_id"].apply(generate_lat_lon))

import pandas as pd
import folium
from IPython.display import display

# --- STEP 1: DEFINE THE REQUIREMENTS (THE LAW) ---
NOISE_LIMITS = {
    'Residential': {'Day': 65, 'Night': 55},  # The 55dBA rule from the prompt
    'Industrial':  {'Day': 80, 'Night': 75},
    'Commercial':  {'Day': 70, 'Night': 65}
}

# --- STEP 2 & 3: THE LOGIC ALGORITHM ---
def evaluate_zone(zone_type, current_noise, duration_loud, current_hour):
    # A. Determine which limit applies (Day vs Night)
    is_night = (current_hour >= 22 or current_hour < 6)
    period = 'Night' if is_night else 'Day'

    limit = NOISE_LIMITS[zone_type][period]

    # B. Compare Noise vs Limit
    status = "Green"
    color = "green"
    alert = "None"

    if current_noise <= (limit - 5):
        status = "Compliant"
        color = "green"
    elif current_noise <= limit:
        status = "Near Limit"
        color = "orange" # Yellow/Orange
    else:
        # It is a VIOLATION (Red)
        status = "Violation"
        color = "red"

        # C. The "Persistence" Check (Requirement #4)
        if duration_loud >= 30:
            alert = "⚠️ PRIORITY ALERT: Persistent Violation (>30m)"
        else:
            alert = "Monitoring Violation..."

    return status, color, alert, limit

# --- MOCK DATA (To test the logic) ---
# We simulate a Residential zone at 11 PM (Night)
# Scenario 1: Loud for 10 mins (No Alert)
# Scenario 2: Loud for 45 mins (SHOULD ALERT)
data = [
    {'id': 1, 'type': 'Residential', 'noise': 60, 'duration': 10},
    {'id': 2, 'type': 'Residential', 'noise': 60, 'duration': 45},
    {'id': 3, 'type': 'Industrial',  'noise': 70, 'duration': 0}
]

CURRENT_HOUR = 23 # 11 PM

# --- RUN THE CHECK ---
print(f"--- VIOLATION REPORT (Time: {CURRENT_HOUR}:00) ---")
for zone in data:
    status, color, alert, limit = evaluate_zone(
        zone['type'], zone['noise'], zone['duration'], CURRENT_HOUR
    )

    print(f"Zone {zone['id']} ({zone['type']}):")
    print(f"  Noise: {zone['noise']} dBA (Limit: {limit})")
    print(f"  Status: {status}")
    print(f"  Action: {alert}")
    print("-" * 20)

import folium
import pandas as pd
import random
import numpy as np

# 1. SETUP
map_center = [12.9716, 77.5946] # Bangalore City Center
NOISE_LIMIT = 55

# ---------------------------------------------------------
# 2. GENERATE 50 RANDOM ZONES (The "Busy Map" Logic)
# ---------------------------------------------------------
zones = []
num_points = 50  # Change this to 100 if you want even more dots!

for i in range(num_points):
    # Randomize Location: Spread points within ~1km of the center
    # 0.02 degrees is roughly 2km
    lat = map_center[0] + random.uniform(-0.02, 0.02)
    lon = map_center[1] + random.uniform(-0.02, 0.02)

    # Randomize Noise: Generate values between 40 dBA (Quiet) and 80 dBA (Loud)
    # We bias it slightly so we get a good mix of colors
    noise_level = random.randint(40, 75)

    # Randomize Zone Type
    z_type = random.choice(['Residential', 'Commercial', 'Industrial'])

    zones.append({
        "id": i+1,
        "lat": lat,
        "lon": lon,
        "noise": noise_level,
        "type": z_type
    })

df = pd.DataFrame(zones)

# ---------------------------------------------------------
# 3. DEFINE COLORS & POPUPS
# ---------------------------------------------------------
def get_status_color(noise_level, limit):
    if noise_level > limit:
        return 'red', 'VIOLATION'
    elif noise_level >= (limit - 5):
        return 'orange', 'NEAR LIMIT'
    else:
        return 'green', 'COMPLIANT'

# 4. DRAW THE MAP
m = folium.Map(location=map_center, zoom_start=13, tiles='cartodbpositron')

# Add Title
title_html = '''<h3 align="center" style="font-size:16px"><b>Project QuietZone: City-Wide Analysis</b></h3>'''
m.get_root().html.add_child(folium.Element(title_html))

for index, row in df.iterrows():
    color, status = get_status_color(row['noise'], NOISE_LIMIT)

    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=8,          # Slightly smaller dots so they don't overlap too much
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7,
        popup=folium.Popup(f"<b>Zone {row['id']}</b><br>Noise: {row['noise']} dBA<br>Status: {status}", max_width=200)
    ).add_to(m)

# 5. LEGEND
legend_html = '''
<div style="position: fixed;
     bottom: 50px; left: 50px; width: 150px; height: 130px;
     border:2px solid grey; z-index:9999; font-size:14px;
     background-color:white; opacity: 0.9;">
     &nbsp;<b>Live Status</b><br>
     &nbsp;<i class="fa fa-circle" style="color:red"></i>&nbsp; Violation<br>
     &nbsp;<i class="fa fa-circle" style="color:orange"></i>&nbsp; Warning<br>
     &nbsp;<i class="fa fa-circle" style="color:green"></i>&nbsp; Safe<br>
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))

# Show Map
m

import pandas as pd
import random
import folium
from IPython.display import display, HTML

# ---------------------------------------------------------
# 1. SETUP & SIMULATE ADVANCED DATA
# ---------------------------------------------------------
# We need more details now: Traffic Density and Time
CURRENT_TIME = 23  # 11:00 PM (Night Rules Apply)
NOISE_LIMIT = 55

zones_data = []
for i in range(10): # Simulating 10 active zones
    # Randomize attributes to create different scenarios
    z_type = random.choice(['Residential', 'Industrial', 'Commercial'])
    traffic_flow = random.choice(['Low', 'Moderate', 'High', 'Gridlock'])
    noise = random.randint(45, 85) # Random noise

    # Assign a fake Business ID for industrial zones
    biz_id = f"FAC-{random.randint(100,999)}" if z_type == 'Industrial' else "N/A"

    zones_data.append({
        "zone_id": i+1,
        "lat": 12.9716 + random.uniform(-0.01, 0.01),
        "lon": 77.5946 + random.uniform(-0.01, 0.01),
        "type": z_type,
        "traffic_density": traffic_flow,
        "noise": noise,
        "business_id": biz_id
    })

df = pd.DataFrame(zones_data)

# ---------------------------------------------------------
# 2. THE MITIGATION ENGINE (The Core Intelligence)
# ---------------------------------------------------------

def mitigation_engine(row):
    # A. Check Compliance First
    if row['noise'] <= NOISE_LIMIT:
        return "Green", "None", "No Action Required"

    # B. If Red/Violation, INFER THE SOURCE
    source = "Unknown"
    policy_action = "Investigate"

    # --- LOGIC TREE ---

    # 1. Traffic Logic: High Traffic + Noise = Traffic Noise
    if row['traffic_density'] in ['High', 'Gridlock']:
        source = "Traffic Congestion"
        policy_action = f"⚠️ AUTO-ACTION: Signal Traffic Control Center to lower speed limit to 30km/h in Zone {row['zone_id']}."

    # 2. Industrial Logic: Low Traffic + Industrial Zone = Factory Noise
    elif row['type'] == 'Industrial':
        source = f"Industrial Machinery ({row['business_id']})"
        policy_action = f"📜 LEGAL: Auto-generate Digital Violation Notice #8842 for Business {row['business_id']}."

    # 3. Commercial Logic: Low Traffic + Commercial Zone = Nightlife/Music
    elif row['type'] == 'Commercial' and CURRENT_TIME >= 22:
        source = "Commercial/Nightlife"
        policy_action = "👮 DISPATCH: Alert nearest Patrol Unit for Noise Ordinance enforcement."

    # 4. Residential Logic: Likely Construction or Private Party
    elif row['type'] == 'Residential':
        source = "Civil Disturbance"
        policy_action = "🔔 ALERT: Send 'Quiet Hours' push notification to residents in Zone."

    return "Red", source, policy_action

# Apply the engine to the dataframe
df[['status', 'inferred_source', 'mitigation_policy']] = df.apply(mitigation_engine, axis=1, result_type='expand')

# ---------------------------------------------------------
# 3. DISPLAY THE "ACTION DASHBOARD"
# ---------------------------------------------------------

# Filter to show only Violations (Where the Engine kicked in)
violations = df[df['status'] == 'Red'][['zone_id', 'type', 'noise', 'traffic_density', 'inferred_source', 'mitigation_policy']]

print("--- 🤖 AUTOMATED MITIGATION POLICY ENGINE OUTPUT ---")
if len(violations) > 0:
    display(violations)
else:
    print("No violations detected. City is quiet.")

# ---------------------------------------------------------
# 4. VISUALIZE ACTIONS ON MAP
# ---------------------------------------------------------
m = folium.Map(location=[12.9716, 77.5946], zoom_start=14, tiles='cartodbpositron')

for _, row in df.iterrows():
    # Color Logic
    color = 'red' if row['status'] == 'Red' else 'green'

    # Complex Popup with the Policy Decision
    popup_text = f"""
    <div style="width:250px">
        <b>Zone {row['zone_id']} ({row['type']})</b><br>
        Noise: {row['noise']} dBA<br>
        Traffic: {row['traffic_density']}<br>
        <hr>
        <b>Source:</b> {row['inferred_source']}<br>
        <b>Action:</b> <span style="color:red">{row['mitigation_policy']}</span>
    </div>
    """

    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=10,
        color=color,
        fill=True,
        fill_color=color,
        popup=folium.Popup(popup_text, max_width=300)
    ).add_to(m)

m

import matplotlib.pyplot as plt

# Data
stages = ['Before Implementation\n(High Traffic)', 'After Quietzone']
noise_levels = [85, 30]
colors = ['#ff6b6b', '#4ecdc4']

fig, ax = plt.subplots(figsize=(10, 7))

# Create bars
bars = ax.bar(stages, noise_levels, color=colors, width=0.5)

# Add data labels
for bar, level in zip(bars, noise_levels):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 2,
            f'{height} dBA',
            ha='center', va='bottom', fontsize=16, fontweight='bold', color='black')

# Calculate exact center between the tops of the two bars
# The first bar is at x=0, the second at x=1, so the center x is 0.5
mid_x = 0.5
# The vertical center is the average of the two heights: (85 + 30) / 2 = 57.5
mid_y = (noise_levels[0] + noise_levels[1]) / 2

# Add text for reduction in the calculated center
ax.text(mid_x, mid_y, '-65% Noise Reduction', ha='center', va='center', fontsize=14, fontweight='bold', color='#1976d2',
        bbox=dict(facecolor='white', edgecolor='#1976d2', boxstyle='round,pad=0.5'))

# Customize styling
ax.set_ylabel('Noise Level (dBA)', fontsize=13)
ax.set_title('Noise Reduction with Quietzone Platform', fontsize=18, fontweight='bold', pad=25)
ax.set_ylim(0, 110)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.3)

plt.tight_layout()
plt.savefig('centered_noise_graph.png', dpi=300)
plt.show()